<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'AppBundle\Controller\GalleryController' shared autowired service.

include_once $this->targetDirs[3].'/src/AppBundle/Controller/GalleryController.php';

return $this->services['AppBundle\Controller\GalleryController'] = new \AppBundle\Controller\GalleryController();
