<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2jrbl3l\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2jrbl3l/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container2jrbl3l.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container2jrbl3l\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container2jrbl3l\appDevDebugProjectContainer(array(
    'container.build_hash' => '2jrbl3l',
    'container.build_id' => '04ef9802',
    'container.build_time' => 1526464912,
), __DIR__.\DIRECTORY_SEPARATOR.'Container2jrbl3l');
