<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZ98eawc\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZ98eawc/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerZ98eawc.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerZ98eawc\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerZ98eawc\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Z98eawc',
    'container.build_id' => '2f880aaf',
    'container.build_time' => 1526634279,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerZ98eawc');
